// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	vaultGetInfo: () => typedError<VaultInfo, ApiError>(__TAURI_INVOKE("vault_get_info")),
	vaultCreate: (password: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("vault_create", { password })),
	vaultUnlockPassword: (password: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("vault_unlock_password", { password })),
	vaultUnlockQuick: () => typedError<PublicVault, ApiError>(__TAURI_INVOKE("vault_unlock_quick")),
	vaultLock: () => typedError<null, ApiError>(__TAURI_INVOKE("vault_lock")),
	vaultChangePassword: (currentPassword: string, newPassword: string) => typedError<null, ApiError>(__TAURI_INVOKE("vault_change_password", { currentPassword, newPassword })),
	vaultSetTouchId: (enabled: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("vault_set_touch_id", { enabled })),
	/**
	 *  Create or update a connection. When creating, the tree node is appended
	 *  to `parent_folder` (or the root). Returns the updated public vault.
	 */
	connectionUpsert: (id: string | null, input: ConnectionInput, parentFolder: string | null) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("connection_upsert", { id, input, parentFolder })),
	connectionSecrets: (id: string) => typedError<ConnectionSecrets, ApiError>(__TAURI_INVOKE("connection_secrets", { id })),
	connectionDuplicate: (id: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("connection_duplicate", { id })),
	connectionDelete: (id: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("connection_delete", { id })),
	folderCreate: (name: string, parentFolder: string | null, badge: {
	kind: BadgeKind,
	/**  Emoji character or hex color like `#e5484d`. */
	value: string,
} | null, agentAccess: "off" | "read_only" | "ask" | "full" | null) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("folder_create", { name, parentFolder, badge, agentAccess })),
	folderUpdate: (id: string, name: string, badge: {
	kind: BadgeKind,
	/**  Emoji character or hex color like `#e5484d`. */
	value: string,
} | null, agentAccess: "off" | "read_only" | "ask" | "full" | null) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("folder_update", { id, name, badge, agentAccess })),
	/**  Delete a folder; its children are lifted to the parent level. */
	folderDelete: (id: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("folder_delete", { id })),
	/**
	 *  Replace the whole tree (drag & drop reordering). Validated against the
	 *  connections map before committing.
	 */
	treeUpdate: (tree: TreeNode[]) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("tree_update", { tree })),
	settingsUpdate: (settings: Settings) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("settings_update", { settings })),
	knownHostRemove: (host: string) => typedError<PublicVault, ApiError>(__TAURI_INVOKE("known_host_remove", { host })),
	/**
	 *  Move the vault to a different path (§8 Vault settings). Requires an
	 *  unlocked vault: the file is re-encrypted and written at the new location,
	 *  the old file stays as a manual backup.
	 */
	vaultSetPath: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("vault_set_path", { path })),
	vaultSwitchPath: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("vault_switch_path", { path })),
	/**  Open a session from one lifecycle-authorized, fully materialized plan. */
	sessionConnect: (connectionId: string) => typedError<SessionDto, ApiError>(__TAURI_INVOKE("session_connect", { connectionId })),
	sessionDisconnect: (sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("session_disconnect", { sessionId })),
	hostKeyAccept: (host: string, port: number, keyLine: string, runtimeContextId: string, vaultAccessEpoch: string) => typedError<null, ApiError>(__TAURI_INVOKE("host_key_accept", { host, port, keyLine, runtimeContextId, vaultAccessEpoch })),
	termOpen: (sessionId: string, cols: number, rows: number, output: Channel<TerminalStreamEvent>) => typedError<string, ApiError>(__TAURI_INVOKE("term_open", { sessionId, cols, rows, output })),
	termWrite: (termId: string, data: string) => typedError<null, ApiError>(__TAURI_INVOKE("term_write", { termId, data })),
	termResize: (termId: string, cols: number, rows: number) => typedError<null, ApiError>(__TAURI_INVOKE("term_resize", { termId, cols, rows })),
	termClose: (termId: string) => typedError<null, ApiError>(__TAURI_INVOKE("term_close", { termId })),
	localList: (path: string) => typedError<RemoteEntry[], ApiError>(__TAURI_INVOKE("local_list", { path })),
	localHome: () => typedError<string, ApiError>(__TAURI_INVOKE("local_home")),
	localMkdir: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("local_mkdir", { path })),
	localCreateFile: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("local_create_file", { path })),
	localRename: (from: string, to: string) => typedError<null, ApiError>(__TAURI_INVOKE("local_rename", { from, to })),
	localDelete: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("local_delete", { path })),
	localChmod: (path: string, mode: number) => typedError<null, ApiError>(__TAURI_INVOKE("local_chmod", { path, mode })),
	/**
	 *  Copy files/dirs into `dest_dir` on the local filesystem (Finder → local
	 *  pane drop). Skips items already inside `dest_dir` (dropped onto self).
	 */
	localCopyInto: (paths: string[], destDir: string) => typedError<null, ApiError>(__TAURI_INVOKE("local_copy_into", { paths, destDir })),
	/**
	 *  Write the drag preview icon to a temp file once and return its path.
	 *  tauri-plugin-drag needs an on-disk image for the OS drag cursor.
	 */
	dragPreviewIcon: () => typedError<string, ApiError>(__TAURI_INVOKE("drag_preview_icon")),
	remoteList: (sessionId: string, path: string) => typedError<RemoteEntry[], ApiError>(__TAURI_INVOKE("remote_list", { sessionId, path })),
	remoteHome: (sessionId: string) => typedError<string, ApiError>(__TAURI_INVOKE("remote_home", { sessionId })),
	remoteMkdir: (sessionId: string, path: string) => typedError<null, ApiError>(__TAURI_INVOKE("remote_mkdir", { sessionId, path })),
	remoteCreateFile: (sessionId: string, path: string) => typedError<null, ApiError>(__TAURI_INVOKE("remote_create_file", { sessionId, path })),
	remoteRename: (sessionId: string, from: string, to: string) => typedError<null, ApiError>(__TAURI_INVOKE("remote_rename", { sessionId, from, to })),
	remoteChmod: (sessionId: string, path: string, mode: number) => typedError<null, ApiError>(__TAURI_INVOKE("remote_chmod", { sessionId, path, mode })),
	/**
	 *  Compare the local tree under `local_path` with the remote tree under
	 *  `remote_path`. Returns as soon as a difference is found; `unknown` means
	 *  the tree could not be verified (too large, or unreadable locally).
	 */
	remoteCompareSubtree: (sessionId: string, localPath: string, remotePath: string, ignoreMtime: boolean, coarseRemoteMtime: boolean, includeHidden: boolean, hideLocalJunk: boolean) => typedError<SubtreeStatus, ApiError>(__TAURI_INVOKE("remote_compare_subtree", { sessionId, localPath, remotePath, ignoreMtime, coarseRemoteMtime, includeHidden, hideLocalJunk })),
	/**
	 *  Cancel every in-flight subtree comparison for a session. Walks notice at
	 *  their next directory boundary.
	 */
	remoteCompareCancel: (sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("remote_compare_cancel", { sessionId })),
	/**
	 *  Whether uploads on this session preserve the local modification time
	 *  (`RemoteFs::preserves_mtime`). When they cannot — S3 always, FTP servers
	 *  without MFMT — the comparison UI falls back to size-only matching.
	 */
	remotePreservesMtime: (sessionId: string) => typedError<boolean, ApiError>(__TAURI_INVOKE("remote_preserves_mtime", { sessionId })),
	/**
	 *  Public/private status for a batch of objects — fetched in the background
	 *  after a listing; failures come back as `unknown`, never as an error.
	 */
	s3AclStatus: (sessionId: string, paths: string[]) => typedError<S3AclEntry[], ApiError>(__TAURI_INVOKE("s3_acl_status", { sessionId, paths })),
	/**
	 *  Make objects public or private; directories apply recursively to every
	 *  object under the prefix. Returns the number of objects changed.
	 */
	s3SetAcl: (sessionId: string, targets: S3AclTarget[], makePublic: boolean) => typedError<number, ApiError>(__TAURI_INVOKE("s3_set_acl", { sessionId, targets, makePublic })),
	s3SetUploadAcl: (sessionId: string, mode: S3UploadAcl, persist: boolean) => typedError<{
	tree: TreeNode[],
	connections: { [key in string]: PublicConnection },
	known_hosts: { [key in string]: string },
	settings: Settings,
} | null, ApiError>(__TAURI_INVOKE("s3_set_upload_acl", { sessionId, mode, persist })),
	transferUpload: (sessionId: string, localPaths: string[], remoteDir: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_upload", { sessionId, localPaths, remoteDir })),
	transferDownload: (sessionId: string, remotePaths: string[], localDir: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_download", { sessionId, remotePaths, localDir })),
	transferList: () => typedError<TransferListDto, ApiError>(__TAURI_INVOKE("transfer_list")),
	transferPause: (id: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_pause", { id })),
	transferResume: (id: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_resume", { id })),
	transferCancel: (id: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_cancel", { id })),
	transferPauseAll: (runtimeContextId: string, sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_pause_all", { runtimeContextId, sessionId })),
	transferResumeAll: (runtimeContextId: string, sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_resume_all", { runtimeContextId, sessionId })),
	transferCancelAll: (runtimeContextId: string, sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_cancel_all", { runtimeContextId, sessionId })),
	transferClearFinished: (runtimeContextId: string, sessionId: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_clear_finished", { runtimeContextId, sessionId })),
	transferResolve: (sessionId: string, id: string, action: ConflictAction, applyToAll: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_resolve", { sessionId, id, action, applyToAll })),
	transferRetry: (id: string) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_retry", { id })),
	transferDelete: (sessionId: string, targets: TreeTarget[]) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_delete", { sessionId, targets })),
	transferChmod: (sessionId: string, targets: TreeTarget[], mode: number, scope: ChmodScope) => typedError<null, ApiError>(__TAURI_INVOKE("transfer_chmod", { sessionId, targets, mode, scope })),
	/**
	 *  Download a remote file into the isolated edit cache, open it in the
	 *  configured editor and auto-upload every save (SPEC §5.3).
	 */
	remoteEditOpen: (sessionId: string, remotePath: string) => typedError<null, ApiError>(__TAURI_INVOKE("remote_edit_open", { sessionId, remotePath })),
	/**
	 *  Drain completed remote-edit outcomes so the UI cannot miss a fast save
	 *  while its event listener is still starting or the window is temporarily hidden.
	 */
	remoteEditNotifications: () => typedError<RemoteEditUploadedEvent[], ApiError>(__TAURI_INVOKE("remote_edit_notifications")),
	tunnelStart: (sessionId: string, name: string, localPort: number, remoteHost: string, remotePort: number) => typedError<TunnelStatus, ApiError>(__TAURI_INVOKE("tunnel_start", { sessionId, name, localPort, remoteHost, remotePort })),
	tunnelStop: (tunnelId: string) => typedError<null, ApiError>(__TAURI_INVOKE("tunnel_stop", { tunnelId })),
	tunnelList: (sessionId: string | null) => typedError<TunnelStatus[], ApiError>(__TAURI_INVOKE("tunnel_list", { sessionId })),
	/**  Throttled user-activity ping for the auto-lock timer (SPEC §2.4). */
	vaultTouchActivity: () => typedError<null, ApiError>(__TAURI_INVOKE("vault_touch_activity")),
	/**
	 *  Export an UNENCRYPTED copy of the configuration without any secrets
	 *  (SPEC §8) — passwords, passphrases and inline keys are omitted.
	 */
	vaultExportConfig: (path: string) => typedError<null, ApiError>(__TAURI_INVOKE("vault_export_config", { path })),
	/**
	 *  Import a config file (a Serverus export or a hand-written file following
	 *  docs/CONFIG_FORMAT.md) into the unlocked vault. Merge semantics live in
	 *  `vault::import`.
	 */
	vaultImportConfig: (path: string) => typedError<ImportReport, ApiError>(__TAURI_INVOKE("vault_import_config", { path })),
	/**
	 *  Read a private key file so the UI can store its text inside the vault
	 *  (the key then travels with vault backups). Validated in `local_fs` —
	 *  only PEM-looking files are returned.
	 */
	sshKeyReadFile: (path: string) => typedError<string, ApiError>(__TAURI_INVOKE("ssh_key_read_file", { path })),
	/**
	 *  Open an http(s) URL in the user's default browser (used by the About
	 *  section). Each OS opener delegates and returns immediately; the URL is
	 *  passed as a single argument, never through a shell.
	 */
	openExternal: (url: string) => typedError<null, ApiError>(__TAURI_INVOKE("open_external", { url })),
	/**
	 *  Answer a pending agent UI request. Returns false when it already
	 *  expired.
	 */
	agentUiRespond: (requestId: string, response: AgentUiResponse) => typedError<boolean, ApiError>(__TAURI_INVOKE("agent_ui_respond", { requestId, response })),
	/**  The user takes a terminal away from the agent. */
	agentTakeOver: (termId: string) => typedError<null, ApiError>(__TAURI_INVOKE("agent_take_over", { termId })),
	/**  The user hands a terminal back to the agent. */
	agentHandBack: (termId: string) => typedError<null, ApiError>(__TAURI_INVOKE("agent_hand_back", { termId })),
	/**  Agent state of every terminal the agent touched, for a UI that starts up. */
	agentTerminalStates: () => typedError<AgentTerminalEvent[], ApiError>(__TAURI_INVOKE("agent_terminal_states")),
	/**  How to register Serverus with an MCP client. */
	agentSetupInfo: () => typedError<AgentSetupInfo, ApiError>(__TAURI_INVOKE("agent_setup_info")),
};

/** Events */
export const events = {
	agentActivityEvent: makeEvent<AgentActivityEvent>("agent-activity-event"),
	agentFsChangedEvent: makeEvent<AgentFsChangedEvent>("agent-fs-changed-event"),
	agentTerminalEvent: makeEvent<AgentTerminalEvent>("agent-terminal-event"),
	agentUiRequestEvent: makeEvent<AgentUiRequestEvent>("agent-ui-request-event"),
	agentUiRequestExpiredEvent: makeEvent<AgentUiRequestExpiredEvent>("agent-ui-request-expired-event"),
	agentVaultChangedEvent: makeEvent<AgentVaultChangedEvent>("agent-vault-changed-event"),
	remoteEditUploadedEvent: makeEvent<RemoteEditUploadedEvent>("remote-edit-uploaded-event"),
	sessionStateEvent: makeEvent<SessionStateEvent>("session-state-event"),
	transferProgressEvent: makeEvent<TransferProgressEvent>("transfer-progress-event"),
	vaultLockedEvent: makeEvent<VaultLockedEvent>("vault-locked-event"),
};

/* Types */
/**
 *  Persisted AI-agent access level of a connection or folder. `None` in the
 *  owning field means "inherit from the enclosing folder" (and, at the top,
 *  `Off`). The policy itself lives in `serverus_domain::agent::access`.
 */
export type AgentAccessLevel = "off" | "read_only" | "ask" | "full";

/**
 *  One entry of the agent activity journal. The same `id` is sent again
 *  when the action finishes.
 */
export type AgentActivityEntry = {
	id: string,
	tool: string,
	summary: string,
	status: AgentActivityStatus,
	detail: string | null,
	/**  Unix milliseconds of the start. */
	at_ms: number,
};

export type AgentActivityEvent = {
	/**  The session the action ran in, when it has one. */
	session_id: string | null,
	connection_id: string | null,
	entry: AgentActivityEntry,
};

export type AgentActivityStatus = "running" | "done" | "failed" | "denied" | 
/**  The agent cancelled the call (or disconnected) before it finished. */
"cancelled";

export type AgentConfirmDecision = "deny" | "once" | 
/**  Allow every action on this server for a while without asking. */
"for_a_while";

/**  Whether an agent may add connections to the vault. */
export type AgentCreateMode = "off" | 
/**  Every new connection needs the user's confirmation. */
"ask" | "allowed";

/**
 *  The agent changed remote paths outside the transfer queue (mkdir,
 *  rename, chmod): panes showing their parents should relist.
 */
export type AgentFsChangedEvent = {
	session_id: string,
	paths: string[],
};

/**
 *  Vault-wide AI agent (MCP) settings. Everything is off by default and for
 *  vaults written before the feature existed.
 */
export type AgentSettings = {
	/**  Serve agents at all. While off, every agent request is refused. */
	enabled?: boolean,
	/**
	 *  Treat every connection as `Full`, regardless of its own level: no
	 *  confirmations, no hidden servers.
	 */
	full_access?: boolean,
	/**
	 *  Whether the agent may add connections (with whatever secrets the
	 *  user asked it to store). Full access implies `Allowed`.
	 */
	create_connections?: AgentCreateMode,
};

/**  How to connect an MCP client to this Serverus. */
export type AgentSetupInfo = {
	/**  Agent access is implemented on this platform. */
	supported: boolean,
	/**  The socket is currently accepting agents. */
	listening: boolean,
	/**  Why it is not listening, when it is not. */
	problem: string | null,
	/**  Executable to register as the MCP server (stdio transport). */
	command: string,
	args: string[],
	/**  Ready-to-paste `claude mcp add …` line. */
	claude_code: string,
	/**  Why `command` will not keep working (a temporary app location). */
	command_warning: string | null,
};

/**  One session tab as the UI sees it. */
export type AgentTabInfo = {
	tab_id: string,
	connection_id: string,
	session_id: string | null,
	/**  `connecting` / `connected` / `error` / `disconnected`. */
	state: string,
	active: boolean,
	/**  The tab's active terminal, when one is open. */
	term_id: string | null,
};

/**
 *  Agent state of one terminal: whether the user holds it and which agent
 *  command (if any) is running in it.
 */
export type AgentTerminalEvent = {
	term_id: string,
	session_id: string,
	running: string | null,
	user_control: boolean,
};

/**  Something only the UI can do or decide, answered via `agent_ui_respond`. */
export type AgentUiRequest = 
/**  Report the open session tabs. */
{ kind: "tabs" } | 
/**
 *  Make sure a connected tab exists — the active one when
 *  `connection_id` is `None` — and report it. With `need_terminal` the
 *  reply also names the tab's active terminal.
 */
{ kind: "open_tab"; connection_id: string | null; need_terminal: boolean } | 
/**  Ask the user to allow one agent action. */
{ kind: "confirm"; connection_id: string; server: string; 
/**  Short imperative summary ("Run a command"). */
action: string; 
/**  The exact command, paths, etc. */
detail: string };

export type AgentUiRequestEvent = {
	request_id: string,
	request: AgentUiRequest,
};

/**
 *  A request the UI was shown ended without an answer (timed out, or the
 *  agent cancelled the call): drop its dialog.
 */
export type AgentUiRequestExpiredEvent = {
	request_id: string,
};

export type AgentUiResponse = { kind: "tabs"; tabs: AgentTabInfo[] } | { kind: "tab"; tab: AgentTabInfo } | { kind: "confirm"; decision: AgentConfirmDecision } | { kind: "error"; message: string };

/**
 *  The agent changed the vault (added a connection): the UI takes the new
 *  secret-free vault and tells the user what happened.
 */
export type AgentVaultChangedEvent = {
	vault: PublicVault,
	summary: string,
};

/**  Serializable error crossing the IPC boundary. */
export type ApiError = {
	code: string,
	message: string,
	host_key: HostKeyPrompt | null,
};

export type AppearanceSettings = {
	theme: ThemePreference,
};

export type AuthMethod = "password" | "key" | "agent";

export type Badge = {
	kind: BadgeKind,
	/**  Emoji character or hex color like `#e5484d`. */
	value: string,
};

export type BadgeKind = "emoji" | "color";

/**  Which entries below the selected directories a recursive chmod touches. */
export type ChmodScope = "files" | "dirs" | "both";

export type ConflictAction = "overwrite" | "skip" | "rename";

export type ConflictPolicy = "ask" | "overwrite" | "skip" | "rename";

/**
 *  Input for creating/updating a connection from the UI. Secret fields are
 *  "tri-state": `None` = keep the stored value, `Some("")` = clear,
 *  `Some(v)` = replace.
 */
export type ConnectionInput = {
	name: string,
	badge: Badge | null,
	protocol: Protocol,
	host: string,
	port: number,
	auth_method: AuthMethod,
	username: string,
	password: string | null,
	key_path: string | null,
	key_inline: string | null,
	key_passphrase: string | null,
	jump_host: string | null,
	ftp: FtpOptions | null,
	s3: S3Options | null,
	remote_dir: string | null,
	local_dir: string | null,
	tunnels: TunnelConfig[],
	disable_terminal?: boolean,
	notes: string,
	/**  `None` inherits the folder's level. */
	agent_access?: AgentAccessLevel | null,
};

/**
 *  Decrypted secrets for one connection, for pre-filling the edit form.
 *  Safe: the vault is already unlocked (master password / Touch ID), and the
 *  values are never persisted outside the encrypted vault.
 */
export type ConnectionSecrets = {
	password: string | null,
	key_passphrase: string | null,
	key_inline: string | null,
};

export type EditorSettings = {
	/**  When false, `custom_app` names the editor application to use. */
	use_system_default: boolean,
	custom_app: string | null,
};

export type FtpOptions = {
	tls: FtpTlsMode,
	passive: boolean,
};

export type FtpTlsMode = "none" | 
/**  Explicit FTPS (AUTH TLS). When set, plaintext fallback is forbidden. */
"explicit";

/**
 *  Host-key confirmation payload attached to a `host_key_prompt` error:
 *  the UI shows the fingerprint dialog and reconnects on acceptance.
 */
export type HostKeyPrompt = {
	/**
	 *  Opaque generation that issued this decision. The UI must return it
	 *  unchanged so a prompt from a retired Vault cannot mutate the current one.
	 */
	runtime_context_id: string,
	/**  Exact unlock epoch that authorized the connection attempt. */
	vault_access_epoch: string,
	host: string,
	port: number,
	algorithm: string,
	fingerprint: string,
	key_line: string,
	/**  A different key was stored before — show the scary red variant. */
	changed: boolean,
};

export type ImportReport = {
	/**  Number of connections created or updated by the import. */
	connections: number,
	vault: PublicVault,
};

export type PanelSettings = {
	show_hidden: boolean,
	/**
	 *  Never show OS metadata junk (`.DS_Store`, `Thumbs.db`) in the local
	 *  pane — regardless of `show_hidden` — keep it out of the local side of
	 *  folder comparison, and leave it out of directory transfers in either
	 *  direction. The remote pane and remote side of comparison still show
	 *  such files so stray uploads surface as differences and can be deleted.
	 *  On by default (also for vaults saved before the setting existed).
	 */
	hide_local_junk?: boolean,
	size_format: SizeFormat,
	default_local_dir: string | null,
	/**
	 *  Sidebar width in CSS pixels, always within
	 *  [`SIDEBAR_WIDTH_MIN`]..=[`SIDEBAR_WIDTH_MAX`].
	 */
	sidebar_width?: number,
};

export type Protocol = 
/**  SSH covers terminal + SFTP + tunnels. */
"ssh" | "ftp" | 
/**  S3-compatible object storage (AWS S3, DigitalOcean Spaces, R2, …). */
"s3";

/**  Auth config with secrets replaced by presence flags. */
export type PublicAuth = {
	method: AuthMethod,
	username: string,
	key_path: string | null,
	has_password: boolean,
	has_key_inline: boolean,
	has_key_passphrase: boolean,
};

export type PublicConnection = {
	id: string,
	name: string,
	badge: Badge | null,
	protocol: Protocol,
	host: string,
	port: number,
	auth: PublicAuth,
	jump_host: string | null,
	ftp: FtpOptions | null,
	s3: S3Options | null,
	remote_dir: string | null,
	local_dir: string | null,
	tunnels: TunnelConfig[],
	disable_terminal: boolean,
	notes: string,
	agent_access: AgentAccessLevel | null,
};

/**  The whole vault as the UI sees it — no secrets. */
export type PublicVault = {
	tree: TreeNode[],
	connections: { [key in string]: PublicConnection },
	known_hosts: { [key in string]: string },
	settings: Settings,
};

/**
 *  A remote-edited file was saved and uploaded back ("Uploaded ✓" toast,
 *  SPEC §5.3). `error` is set when the auto-upload failed.
 */
export type RemoteEditUploadedEvent = {
	name: string,
	remote_path: string,
	error: string | null,
};

export type RemoteEntry = {
	name: string,
	/**  Absolute remote path. */
	path: string,
	is_dir: boolean,
	is_symlink: boolean,
	size: number,
	/**  Unix seconds. */
	mtime: number | null,
	/**  Unix permission bits (lower 12 bits meaningful), when known. */
	permissions: number | null,
};

export type S3AclEntry = {
	path: string,
	status: S3AclStatus,
};

export type S3AclStatus = "public" | "private" | 
/**  The provider rejected GetObjectAcl (e.g. R2) or the request failed. */
"unknown";

export type S3AclTarget = {
	path: string,
	is_dir: boolean,
};

export type S3Options = {
	/**
	 *  Signing region. Providers other than AWS often accept any value;
	 *  empty falls back to `us-east-1`.
	 */
	region?: string | null,
	/**
	 *  Lock the connection to one bucket. Empty = the root of the panel
	 *  lists all buckets of the account as folders.
	 */
	bucket?: string | null,
	/**
	 *  Path-style addressing (`https://endpoint/bucket/key`) for MinIO and
	 *  other self-hosted gateways; default is virtual-host style.
	 */
	path_style?: boolean,
	/**
	 *  Base for "Copy public URL" (CDN endpoint / custom domain). Empty =
	 *  build the URL from the storage endpoint.
	 */
	public_base_url?: string | null,
	upload_acl: S3UploadAcl,
};

/**  Default ACL applied to objects uploaded to an S3 connection (SPEC §4.4). */
export type S3UploadAcl = "private" | "public_read" | 
/**  The UI asks per upload batch. */
"ask";

export type SecuritySettings = {
	/**  0 = never. */
	auto_lock_minutes: number,
	lock_on_sleep: boolean,
	touch_id: boolean,
};

export type SessionDto = {
	session_id: string,
	connection_id: string,
};

/**  Session lifecycle: `connecting` → `connected` → `disconnected` / `error`. */
export type SessionStateEvent = {
	session_id: string,
	connection_id: string,
	state: string,
	message: string | null,
};

export type Settings = {
	/**  Missing in vaults written before theme selection was introduced. */
	appearance?: AppearanceSettings,
	security: SecuritySettings,
	transfers: TransferSettings,
	editor: EditorSettings,
	terminal: TerminalSettings,
	panels: PanelSettings,
	/**  Missing in vaults written before AI agent access existed. */
	agent?: AgentSettings,
};

export type SizeFormat = 
/**  Powers of 1000 (KB). */
"kb" | 
/**  Powers of 1024 (KiB). */
"kib";

export type SubtreeStatus = "matching" | "different" | 
/**
 *  Could not be verified: the tree is over [`MAX_COMPARED_ENTRIES`] or a
 *  local directory was unreadable. Deliberately not "matching".
 */
"unknown";

export type TerminalSettings = {
	font_family: string,
	font_size: number,
	scrollback: number,
	/**
	 *  Copy the selection to the clipboard automatically. Off by default —
	 *  it silently clobbers whatever the user copied elsewhere.
	 */
	copy_on_select?: boolean,
};

export type TerminalStreamEvent = { kind: "data"; data: string } | { kind: "exit" };

export type ThemePreference = "system" | "light" | "dark";

export type TransferKind = "upload" | "download" | 
/**  Recursive delete of a remote entry (no bytes move). */
"delete" | 
/**  Recursive chmod of a remote directory (no bytes move). */
"chmod";

export type TransferListDto = {
	runtime_context_id: string,
	items: TransferSnapshot[],
	summary: TransferSummary,
	/**  Exact per-session counts — the transfer panel is rendered per tab. */
	session_summaries: { [key in string]: TransferSummary },
};

/**  Periodic transfer queue snapshot (~4 Hz while transfers are active). */
export type TransferProgressEvent = {
	runtime_context_id: string,
	items: TransferSnapshot[],
	summary: TransferSummary,
	/**  Exact per-session counts — the transfer panel is rendered per tab. */
	session_summaries: { [key in string]: TransferSummary },
};

export type TransferSettings = {
	max_parallel_per_server: number,
	conflict_policy: ConflictPolicy,
	preserve_mtime: boolean,
	tar_acceleration: boolean,
};

export type TransferSnapshot = {
	id: string,
	session_id: string,
	kind: TransferKind,
	state: TransferState,
	error: string | null,
	name: string,
	local_path: string,
	remote_path: string,
	accelerated: boolean,
	/**  Tree operations: still discovering entries, `total` keeps growing. */
	scanning: boolean,
	/**  Bytes for transfers, entries for tree operations. */
	done: number,
	total: number,
	speed_bps: number,
};

export type TransferState = "queued" | "running" | "paused" | 
/**  Waiting for the user's overwrite/skip/rename decision. */
"conflict" | "done" | "skipped" | "cancelled" | "error";

export type TransferSummary = {
	queued: number,
	running: number,
	done: number,
	failed: number,
	total_items: number,
};

/**
 *  Sidebar tree node. Folders nest arbitrarily; connection nodes are
 *  references into [`super::VaultPayload::connections`].
 */
export type TreeNode = { type: "folder"; id: string; name: string; badge?: Badge | null; children?: TreeNode[]; 
/**
 *  Sidebar disclosure state. Expanded is the default, so `false` is
 *  also the right value for vaults written before this existed.
 */
collapsed?: boolean; 
/**
 *  AI agent access inherited by everything inside that does not set
 *  its own; `None` inherits from the parent folder.
 */
agent_access?: AgentAccessLevel | null } | { type: "connection"; id: string };

/**
 *  One selected entry. `is_dir` means a real directory: a symlink to one is
 *  removed as a link, never descended.
 */
export type TreeTarget = {
	path: string,
	is_dir: boolean,
};

export type TunnelConfig = {
	name: string,
	kind: TunnelKind,
	local_port: number,
	remote_host: string,
	remote_port: number,
	autostart?: boolean,
};

export type TunnelKind = 
/**  `localhost:<local_port>` → SSH → `<remote_host>:<remote_port>`. */
"local";

export type TunnelStatus = {
	id: string,
	session_id: string,
	name: string,
	local_port: number,
	remote_host: string,
	remote_port: number,
	bytes_up: number,
	bytes_down: number,
	connections: number,
};

export type VaultInfo = {
	path: string,
	exists: boolean,
	unlocked: boolean,
	biometry_available: boolean,
	/**
	 *  A DEK for this vault is stored behind biometrics — Touch ID unlock
	 *  can be offered right away.
	 */
	quick_unlock_ready: boolean,
	/**
	 *  UI label for the platform's quick-unlock mechanism
	 *  ("Touch ID" / "Windows Hello").
	 */
	quick_unlock_method: string,
	/**
	 *  True only in `scenario-tests` builds. The lock screen shows a typed
	 *  vault-path field then — WebDriver cannot drive the native file
	 *  pickers — and hides it from real users otherwise.
	 */
	scenario_build: boolean,
};

/**  The vault was locked (auto-lock, sleep, or explicit). */
export type VaultLockedEvent = null;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

