//! Documents, archives and packages, certificates, and 3D/CAD.

/// See [`super::MEDIA_TYPES`] for the invariants every group obeys.
pub(super) const TYPES: &[(&[&str], &str)] = &[
    // ── Documents ───────────────────────────────────────────────────────
    (&["pdf"], "application/pdf"),
    (&["rtf"], "application/rtf"),
    (&["doc", "dot"], "application/msword"),
    (
        &["docx"],
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ),
    (
        &["dotx"],
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    ),
    (
        &["docm"],
        "application/vnd.ms-word.document.macroEnabled.12",
    ),
    (&["xls", "xlt", "xla"], "application/vnd.ms-excel"),
    (
        &["xlsx"],
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ),
    (
        &["xltx"],
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    ),
    (&["xlsm"], "application/vnd.ms-excel.sheet.macroEnabled.12"),
    (
        &["xlsb"],
        "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
    ),
    (
        &["ppt", "pot", "pps", "ppa"],
        "application/vnd.ms-powerpoint",
    ),
    (
        &["pptx"],
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ),
    (
        &["potx"],
        "application/vnd.openxmlformats-officedocument.presentationml.template",
    ),
    (
        &["ppsx"],
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    ),
    (
        &["pptm"],
        "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    ),
    (&["odt"], "application/vnd.oasis.opendocument.text"),
    (&["ods"], "application/vnd.oasis.opendocument.spreadsheet"),
    (&["odp"], "application/vnd.oasis.opendocument.presentation"),
    (&["odg"], "application/vnd.oasis.opendocument.graphics"),
    (&["odf"], "application/vnd.oasis.opendocument.formula"),
    (&["pages"], "application/vnd.apple.pages"),
    (&["numbers"], "application/vnd.apple.numbers"),
    (&["epub"], "application/epub+zip"),
    (&["mobi"], "application/x-mobipocket-ebook"),
    (&["azw", "azw3"], "application/vnd.amazon.ebook"),
    (&["fb2"], "application/x-fictionbook+xml"),
    (&["chm"], "application/vnd.ms-htmlhelp"),
    (&["tex"], "application/x-tex"),
    (&["vsd"], "application/vnd.visio"),
    (&["vsdx"], "application/vnd.ms-visio.drawing"),
    (&["mpp"], "application/vnd.ms-project"),
    (&["one"], "application/onenote"),
    (&["wpd"], "application/vnd.wordperfect"),
    (&["xps"], "application/vnd.ms-xpsdocument"),
    (&["oxps"], "application/oxps"),
    // ── Archives, disk images, packages ─────────────────────────────────
    (&["zip"], "application/zip"),
    (&["gz", "tgz"], "application/gzip"),
    (&["tar"], "application/x-tar"),
    (&["bz2", "tbz2"], "application/x-bzip2"),
    (&["xz"], "application/x-xz"),
    (&["zst"], "application/zstd"),
    (&["lz"], "application/x-lzip"),
    (&["lzma"], "application/x-lzma"),
    (&["lz4"], "application/x-lz4"),
    (&["z"], "application/x-compress"),
    (&["7z"], "application/x-7z-compressed"),
    (&["rar"], "application/vnd.rar"),
    (&["cab"], "application/vnd.ms-cab-compressed"),
    (&["iso"], "application/x-iso9660-image"),
    (&["dmg"], "application/x-apple-diskimage"),
    (&["deb"], "application/vnd.debian.binary-package"),
    (&["rpm"], "application/x-rpm"),
    (&["apk"], "application/vnd.android.package-archive"),
    (&["xpi"], "application/x-xpinstall"),
    (&["msi"], "application/x-msi"),
    (
        &["exe", "dll"],
        "application/vnd.microsoft.portable-executable",
    ),
    (&["jar", "war", "ear"], "application/java-archive"),
    (&["swf"], "application/x-shockwave-flash"),
    // ── Certificates. Private keys are deliberately absent — see below.
    (&["pem"], "application/x-pem-file"),
    (&["crt", "cer", "der"], "application/x-x509-ca-cert"),
    (&["csr"], "application/pkcs10"),
    (&["p12", "pfx"], "application/x-pkcs12"),
    (&["p7b", "p7c"], "application/pkcs7-mime"),
    // ── 3D and CAD ──────────────────────────────────────────────────────
    (&["stl"], "model/stl"),
    (&["obj"], "model/obj"),
    (&["mtl"], "model/mtl"),
    (&["gltf"], "model/gltf+json"),
    (&["glb"], "model/gltf-binary"),
    (&["dae"], "model/vnd.collada+xml"),
    (&["3mf"], "model/3mf"),
    (&["usdz"], "model/vnd.usdz+zip"),
    (&["dwg"], "image/vnd.dwg"),
    (&["dxf"], "image/vnd.dxf"),
];
